services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:

    KimaiPlugin\ApprovalBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'

    KimaiPlugin\ApprovalBundle\API\:
        resource: '../../API'
        tags: ['controller.service_arguments']
